@startuml
|Slutkunde|
start
:Kunde bestiller carport;

|Sælger|
:Sælger modtager ordre;

|Beregningssystem A|
:Beregningssystem A laver tilbud;

|Slutkunde|
:Accept af tilbud;

|Sælger|
:Sælger accepterer tilbud;

|Beregningssystem B|
:Beregningssystem B laver styk/plukliste;

|Lager|
:Lager modtager liste;

|Slutkunde|
:Slutkunde informeres;

stop
@enduml
